# Generated by Django 4.0.5 on 2022-08-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='categorieV',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='effectuerdonnature',
            name='categorieV',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
